# coding: utf-8

"""
    Betfair: Exchange Streaming API

    API to receive streamed updates. This is an ssl socket connection of CRLF delimited json messages (see RequestMessage & ResponseMessage)

    OpenAPI spec version: 1.0.1423
    Contact: bdp@betfair.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class MarketDefinition(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, venue=None, race_type=None, settled_time=None, timezone=None, each_way_divisor=None, regulators=None, market_type=None, market_base_rate=None, number_of_winners=None, country_code=None, line_max_unit=None, in_play=None, bet_delay=None, bsp_market=None, betting_type=None, number_of_active_runners=None, line_min_unit=None, event_id=None, cross_matching=None, runners_voidable=None, turn_in_play_enabled=None, price_ladder_definition=None, key_line_definition=None, suspend_time=None, discount_allowed=None, persistence_enabled=None, runners=None, version=None, event_type_id=None, complete=None, open_date=None, market_time=None, bsp_reconciled=None, line_interval=None, status=None):
        """
        MarketDefinition - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'venue': 'str',
            'race_type': 'str',
            'settled_time': 'datetime',
            'timezone': 'str',
            'each_way_divisor': 'float',
            'regulators': 'list[str]',
            'market_type': 'str',
            'market_base_rate': 'float',
            'number_of_winners': 'int',
            'country_code': 'str',
            'line_max_unit': 'float',
            'in_play': 'bool',
            'bet_delay': 'int',
            'bsp_market': 'bool',
            'betting_type': 'str',
            'number_of_active_runners': 'int',
            'line_min_unit': 'float',
            'event_id': 'str',
            'cross_matching': 'bool',
            'runners_voidable': 'bool',
            'turn_in_play_enabled': 'bool',
            'price_ladder_definition': 'PriceLadderDefinition',
            'key_line_definition': 'KeyLineDefinition',
            'suspend_time': 'datetime',
            'discount_allowed': 'bool',
            'persistence_enabled': 'bool',
            'runners': 'list[RunnerDefinition]',
            'version': 'int',
            'event_type_id': 'str',
            'complete': 'bool',
            'open_date': 'datetime',
            'market_time': 'datetime',
            'bsp_reconciled': 'bool',
            'line_interval': 'float',
            'status': 'str'
        }

        self.attribute_map = {
            'venue': 'venue',
            'race_type': 'raceType',
            'settled_time': 'settledTime',
            'timezone': 'timezone',
            'each_way_divisor': 'eachWayDivisor',
            'regulators': 'regulators',
            'market_type': 'marketType',
            'market_base_rate': 'marketBaseRate',
            'number_of_winners': 'numberOfWinners',
            'country_code': 'countryCode',
            'line_max_unit': 'lineMaxUnit',
            'in_play': 'inPlay',
            'bet_delay': 'betDelay',
            'bsp_market': 'bspMarket',
            'betting_type': 'bettingType',
            'number_of_active_runners': 'numberOfActiveRunners',
            'line_min_unit': 'lineMinUnit',
            'event_id': 'eventId',
            'cross_matching': 'crossMatching',
            'runners_voidable': 'runnersVoidable',
            'turn_in_play_enabled': 'turnInPlayEnabled',
            'price_ladder_definition': 'priceLadderDefinition',
            'key_line_definition': 'keyLineDefinition',
            'suspend_time': 'suspendTime',
            'discount_allowed': 'discountAllowed',
            'persistence_enabled': 'persistenceEnabled',
            'runners': 'runners',
            'version': 'version',
            'event_type_id': 'eventTypeId',
            'complete': 'complete',
            'open_date': 'openDate',
            'market_time': 'marketTime',
            'bsp_reconciled': 'bspReconciled',
            'line_interval': 'lineInterval',
            'status': 'status'
        }

        self._venue = venue
        self._race_type = race_type
        self._settled_time = settled_time
        self._timezone = timezone
        self._each_way_divisor = each_way_divisor
        self._regulators = regulators
        self._market_type = market_type
        self._market_base_rate = market_base_rate
        self._number_of_winners = number_of_winners
        self._country_code = country_code
        self._line_max_unit = line_max_unit
        self._in_play = in_play
        self._bet_delay = bet_delay
        self._bsp_market = bsp_market
        self._betting_type = betting_type
        self._number_of_active_runners = number_of_active_runners
        self._line_min_unit = line_min_unit
        self._event_id = event_id
        self._cross_matching = cross_matching
        self._runners_voidable = runners_voidable
        self._turn_in_play_enabled = turn_in_play_enabled
        self._price_ladder_definition = price_ladder_definition
        self._key_line_definition = key_line_definition
        self._suspend_time = suspend_time
        self._discount_allowed = discount_allowed
        self._persistence_enabled = persistence_enabled
        self._runners = runners
        self._version = version
        self._event_type_id = event_type_id
        self._complete = complete
        self._open_date = open_date
        self._market_time = market_time
        self._bsp_reconciled = bsp_reconciled
        self._line_interval = line_interval
        self._status = status

    @property
    def venue(self):
        """
        Gets the venue of this MarketDefinition.


        :return: The venue of this MarketDefinition.
        :rtype: str
        """
        return self._venue

    @venue.setter
    def venue(self, venue):
        """
        Sets the venue of this MarketDefinition.


        :param venue: The venue of this MarketDefinition.
        :type: str
        """

        self._venue = venue

    @property
    def race_type(self):
        """
        Gets the race_type of this MarketDefinition.


        :return: The race_type of this MarketDefinition.
        :rtype: str
        """
        return self._race_type

    @race_type.setter
    def race_type(self, race_type):
        """
        Sets the race_type of this MarketDefinition.


        :param race_type: The race_type of this MarketDefinition.
        :type: str
        """

        self._race_type = race_type

    @property
    def settled_time(self):
        """
        Gets the settled_time of this MarketDefinition.


        :return: The settled_time of this MarketDefinition.
        :rtype: datetime
        """
        return self._settled_time

    @settled_time.setter
    def settled_time(self, settled_time):
        """
        Sets the settled_time of this MarketDefinition.


        :param settled_time: The settled_time of this MarketDefinition.
        :type: datetime
        """

        self._settled_time = settled_time

    @property
    def timezone(self):
        """
        Gets the timezone of this MarketDefinition.


        :return: The timezone of this MarketDefinition.
        :rtype: str
        """
        return self._timezone

    @timezone.setter
    def timezone(self, timezone):
        """
        Sets the timezone of this MarketDefinition.


        :param timezone: The timezone of this MarketDefinition.
        :type: str
        """

        self._timezone = timezone

    @property
    def each_way_divisor(self):
        """
        Gets the each_way_divisor of this MarketDefinition.


        :return: The each_way_divisor of this MarketDefinition.
        :rtype: float
        """
        return self._each_way_divisor

    @each_way_divisor.setter
    def each_way_divisor(self, each_way_divisor):
        """
        Sets the each_way_divisor of this MarketDefinition.


        :param each_way_divisor: The each_way_divisor of this MarketDefinition.
        :type: float
        """

        self._each_way_divisor = each_way_divisor

    @property
    def regulators(self):
        """
        Gets the regulators of this MarketDefinition.
        The market regulators.

        :return: The regulators of this MarketDefinition.
        :rtype: list[str]
        """
        return self._regulators

    @regulators.setter
    def regulators(self, regulators):
        """
        Sets the regulators of this MarketDefinition.
        The market regulators.

        :param regulators: The regulators of this MarketDefinition.
        :type: list[str]
        """

        self._regulators = regulators

    @property
    def market_type(self):
        """
        Gets the market_type of this MarketDefinition.


        :return: The market_type of this MarketDefinition.
        :rtype: str
        """
        return self._market_type

    @market_type.setter
    def market_type(self, market_type):
        """
        Sets the market_type of this MarketDefinition.


        :param market_type: The market_type of this MarketDefinition.
        :type: str
        """

        self._market_type = market_type

    @property
    def market_base_rate(self):
        """
        Gets the market_base_rate of this MarketDefinition.


        :return: The market_base_rate of this MarketDefinition.
        :rtype: float
        """
        return self._market_base_rate

    @market_base_rate.setter
    def market_base_rate(self, market_base_rate):
        """
        Sets the market_base_rate of this MarketDefinition.


        :param market_base_rate: The market_base_rate of this MarketDefinition.
        :type: float
        """

        self._market_base_rate = market_base_rate

    @property
    def number_of_winners(self):
        """
        Gets the number_of_winners of this MarketDefinition.


        :return: The number_of_winners of this MarketDefinition.
        :rtype: int
        """
        return self._number_of_winners

    @number_of_winners.setter
    def number_of_winners(self, number_of_winners):
        """
        Sets the number_of_winners of this MarketDefinition.


        :param number_of_winners: The number_of_winners of this MarketDefinition.
        :type: int
        """

        self._number_of_winners = number_of_winners

    @property
    def country_code(self):
        """
        Gets the country_code of this MarketDefinition.


        :return: The country_code of this MarketDefinition.
        :rtype: str
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code):
        """
        Sets the country_code of this MarketDefinition.


        :param country_code: The country_code of this MarketDefinition.
        :type: str
        """

        self._country_code = country_code

    @property
    def line_max_unit(self):
        """
        Gets the line_max_unit of this MarketDefinition.
        For Handicap and Line markets, the maximum value for the outcome, in market units for this market (eg 100 runs).

        :return: The line_max_unit of this MarketDefinition.
        :rtype: float
        """
        return self._line_max_unit

    @line_max_unit.setter
    def line_max_unit(self, line_max_unit):
        """
        Sets the line_max_unit of this MarketDefinition.
        For Handicap and Line markets, the maximum value for the outcome, in market units for this market (eg 100 runs).

        :param line_max_unit: The line_max_unit of this MarketDefinition.
        :type: float
        """

        self._line_max_unit = line_max_unit

    @property
    def in_play(self):
        """
        Gets the in_play of this MarketDefinition.


        :return: The in_play of this MarketDefinition.
        :rtype: bool
        """
        return self._in_play

    @in_play.setter
    def in_play(self, in_play):
        """
        Sets the in_play of this MarketDefinition.


        :param in_play: The in_play of this MarketDefinition.
        :type: bool
        """

        self._in_play = in_play

    @property
    def bet_delay(self):
        """
        Gets the bet_delay of this MarketDefinition.


        :return: The bet_delay of this MarketDefinition.
        :rtype: int
        """
        return self._bet_delay

    @bet_delay.setter
    def bet_delay(self, bet_delay):
        """
        Sets the bet_delay of this MarketDefinition.


        :param bet_delay: The bet_delay of this MarketDefinition.
        :type: int
        """

        self._bet_delay = bet_delay

    @property
    def bsp_market(self):
        """
        Gets the bsp_market of this MarketDefinition.


        :return: The bsp_market of this MarketDefinition.
        :rtype: bool
        """
        return self._bsp_market

    @bsp_market.setter
    def bsp_market(self, bsp_market):
        """
        Sets the bsp_market of this MarketDefinition.


        :param bsp_market: The bsp_market of this MarketDefinition.
        :type: bool
        """

        self._bsp_market = bsp_market

    @property
    def betting_type(self):
        """
        Gets the betting_type of this MarketDefinition.


        :return: The betting_type of this MarketDefinition.
        :rtype: str
        """
        return self._betting_type

    @betting_type.setter
    def betting_type(self, betting_type):
        """
        Sets the betting_type of this MarketDefinition.


        :param betting_type: The betting_type of this MarketDefinition.
        :type: str
        """
        allowed_values = ["ODDS", "LINE", "RANGE", "ASIAN_HANDICAP_DOUBLE_LINE", "ASIAN_HANDICAP_SINGLE_LINE"]
        if betting_type not in allowed_values:
            raise ValueError(
                "Invalid value for `betting_type` ({0}), must be one of {1}"
                .format(betting_type, allowed_values)
            )

        self._betting_type = betting_type

    @property
    def number_of_active_runners(self):
        """
        Gets the number_of_active_runners of this MarketDefinition.


        :return: The number_of_active_runners of this MarketDefinition.
        :rtype: int
        """
        return self._number_of_active_runners

    @number_of_active_runners.setter
    def number_of_active_runners(self, number_of_active_runners):
        """
        Sets the number_of_active_runners of this MarketDefinition.


        :param number_of_active_runners: The number_of_active_runners of this MarketDefinition.
        :type: int
        """

        self._number_of_active_runners = number_of_active_runners

    @property
    def line_min_unit(self):
        """
        Gets the line_min_unit of this MarketDefinition.
        For Handicap and Line markets, the minimum value for the outcome, in market units for this market (eg 0 runs).

        :return: The line_min_unit of this MarketDefinition.
        :rtype: float
        """
        return self._line_min_unit

    @line_min_unit.setter
    def line_min_unit(self, line_min_unit):
        """
        Sets the line_min_unit of this MarketDefinition.
        For Handicap and Line markets, the minimum value for the outcome, in market units for this market (eg 0 runs).

        :param line_min_unit: The line_min_unit of this MarketDefinition.
        :type: float
        """

        self._line_min_unit = line_min_unit

    @property
    def event_id(self):
        """
        Gets the event_id of this MarketDefinition.


        :return: The event_id of this MarketDefinition.
        :rtype: str
        """
        return self._event_id

    @event_id.setter
    def event_id(self, event_id):
        """
        Sets the event_id of this MarketDefinition.


        :param event_id: The event_id of this MarketDefinition.
        :type: str
        """

        self._event_id = event_id

    @property
    def cross_matching(self):
        """
        Gets the cross_matching of this MarketDefinition.


        :return: The cross_matching of this MarketDefinition.
        :rtype: bool
        """
        return self._cross_matching

    @cross_matching.setter
    def cross_matching(self, cross_matching):
        """
        Sets the cross_matching of this MarketDefinition.


        :param cross_matching: The cross_matching of this MarketDefinition.
        :type: bool
        """

        self._cross_matching = cross_matching

    @property
    def runners_voidable(self):
        """
        Gets the runners_voidable of this MarketDefinition.


        :return: The runners_voidable of this MarketDefinition.
        :rtype: bool
        """
        return self._runners_voidable

    @runners_voidable.setter
    def runners_voidable(self, runners_voidable):
        """
        Sets the runners_voidable of this MarketDefinition.


        :param runners_voidable: The runners_voidable of this MarketDefinition.
        :type: bool
        """

        self._runners_voidable = runners_voidable

    @property
    def turn_in_play_enabled(self):
        """
        Gets the turn_in_play_enabled of this MarketDefinition.


        :return: The turn_in_play_enabled of this MarketDefinition.
        :rtype: bool
        """
        return self._turn_in_play_enabled

    @turn_in_play_enabled.setter
    def turn_in_play_enabled(self, turn_in_play_enabled):
        """
        Sets the turn_in_play_enabled of this MarketDefinition.


        :param turn_in_play_enabled: The turn_in_play_enabled of this MarketDefinition.
        :type: bool
        """

        self._turn_in_play_enabled = turn_in_play_enabled

    @property
    def price_ladder_definition(self):
        """
        Gets the price_ladder_definition of this MarketDefinition.
        Definition of the price ladder type and any related data.

        :return: The price_ladder_definition of this MarketDefinition.
        :rtype: PriceLadderDefinition
        """
        return self._price_ladder_definition

    @price_ladder_definition.setter
    def price_ladder_definition(self, price_ladder_definition):
        """
        Sets the price_ladder_definition of this MarketDefinition.
        Definition of the price ladder type and any related data.

        :param price_ladder_definition: The price_ladder_definition of this MarketDefinition.
        :type: PriceLadderDefinition
        """

        self._price_ladder_definition = price_ladder_definition

    @property
    def key_line_definition(self):
        """
        Gets the key_line_definition of this MarketDefinition.
        Definition of a markets key line selection (for valid markets), comprising the selectionId and handicap of the team it is applied to.

        :return: The key_line_definition of this MarketDefinition.
        :rtype: KeyLineDefinition
        """
        return self._key_line_definition

    @key_line_definition.setter
    def key_line_definition(self, key_line_definition):
        """
        Sets the key_line_definition of this MarketDefinition.
        Definition of a markets key line selection (for valid markets), comprising the selectionId and handicap of the team it is applied to.

        :param key_line_definition: The key_line_definition of this MarketDefinition.
        :type: KeyLineDefinition
        """

        self._key_line_definition = key_line_definition

    @property
    def suspend_time(self):
        """
        Gets the suspend_time of this MarketDefinition.


        :return: The suspend_time of this MarketDefinition.
        :rtype: datetime
        """
        return self._suspend_time

    @suspend_time.setter
    def suspend_time(self, suspend_time):
        """
        Sets the suspend_time of this MarketDefinition.


        :param suspend_time: The suspend_time of this MarketDefinition.
        :type: datetime
        """

        self._suspend_time = suspend_time

    @property
    def discount_allowed(self):
        """
        Gets the discount_allowed of this MarketDefinition.


        :return: The discount_allowed of this MarketDefinition.
        :rtype: bool
        """
        return self._discount_allowed

    @discount_allowed.setter
    def discount_allowed(self, discount_allowed):
        """
        Sets the discount_allowed of this MarketDefinition.


        :param discount_allowed: The discount_allowed of this MarketDefinition.
        :type: bool
        """

        self._discount_allowed = discount_allowed

    @property
    def persistence_enabled(self):
        """
        Gets the persistence_enabled of this MarketDefinition.


        :return: The persistence_enabled of this MarketDefinition.
        :rtype: bool
        """
        return self._persistence_enabled

    @persistence_enabled.setter
    def persistence_enabled(self, persistence_enabled):
        """
        Sets the persistence_enabled of this MarketDefinition.


        :param persistence_enabled: The persistence_enabled of this MarketDefinition.
        :type: bool
        """

        self._persistence_enabled = persistence_enabled

    @property
    def runners(self):
        """
        Gets the runners of this MarketDefinition.


        :return: The runners of this MarketDefinition.
        :rtype: list[RunnerDefinition]
        """
        return self._runners

    @runners.setter
    def runners(self, runners):
        """
        Sets the runners of this MarketDefinition.


        :param runners: The runners of this MarketDefinition.
        :type: list[RunnerDefinition]
        """

        self._runners = runners

    @property
    def version(self):
        """
        Gets the version of this MarketDefinition.


        :return: The version of this MarketDefinition.
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """
        Sets the version of this MarketDefinition.


        :param version: The version of this MarketDefinition.
        :type: int
        """

        self._version = version

    @property
    def event_type_id(self):
        """
        Gets the event_type_id of this MarketDefinition.
        The Event Type the market is contained within.

        :return: The event_type_id of this MarketDefinition.
        :rtype: str
        """
        return self._event_type_id

    @event_type_id.setter
    def event_type_id(self, event_type_id):
        """
        Sets the event_type_id of this MarketDefinition.
        The Event Type the market is contained within.

        :param event_type_id: The event_type_id of this MarketDefinition.
        :type: str
        """

        self._event_type_id = event_type_id

    @property
    def complete(self):
        """
        Gets the complete of this MarketDefinition.


        :return: The complete of this MarketDefinition.
        :rtype: bool
        """
        return self._complete

    @complete.setter
    def complete(self, complete):
        """
        Sets the complete of this MarketDefinition.


        :param complete: The complete of this MarketDefinition.
        :type: bool
        """

        self._complete = complete

    @property
    def open_date(self):
        """
        Gets the open_date of this MarketDefinition.


        :return: The open_date of this MarketDefinition.
        :rtype: datetime
        """
        return self._open_date

    @open_date.setter
    def open_date(self, open_date):
        """
        Sets the open_date of this MarketDefinition.


        :param open_date: The open_date of this MarketDefinition.
        :type: datetime
        """

        self._open_date = open_date

    @property
    def market_time(self):
        """
        Gets the market_time of this MarketDefinition.


        :return: The market_time of this MarketDefinition.
        :rtype: datetime
        """
        return self._market_time

    @market_time.setter
    def market_time(self, market_time):
        """
        Sets the market_time of this MarketDefinition.


        :param market_time: The market_time of this MarketDefinition.
        :type: datetime
        """

        self._market_time = market_time

    @property
    def bsp_reconciled(self):
        """
        Gets the bsp_reconciled of this MarketDefinition.


        :return: The bsp_reconciled of this MarketDefinition.
        :rtype: bool
        """
        return self._bsp_reconciled

    @bsp_reconciled.setter
    def bsp_reconciled(self, bsp_reconciled):
        """
        Sets the bsp_reconciled of this MarketDefinition.


        :param bsp_reconciled: The bsp_reconciled of this MarketDefinition.
        :type: bool
        """

        self._bsp_reconciled = bsp_reconciled

    @property
    def line_interval(self):
        """
        Gets the line_interval of this MarketDefinition.
        For Handicap and Line markets, the lines available on this market will be between the range of lineMinUnit and lineMaxUnit, in increments of the lineInterval value. e.g. If unit is runs, lineMinUnit=10, lineMaxUnit=20 and lineInterval=0.5, then valid lines include 10, 10.5, 11, 11.5 up to 20 runs.

        :return: The line_interval of this MarketDefinition.
        :rtype: float
        """
        return self._line_interval

    @line_interval.setter
    def line_interval(self, line_interval):
        """
        Sets the line_interval of this MarketDefinition.
        For Handicap and Line markets, the lines available on this market will be between the range of lineMinUnit and lineMaxUnit, in increments of the lineInterval value. e.g. If unit is runs, lineMinUnit=10, lineMaxUnit=20 and lineInterval=0.5, then valid lines include 10, 10.5, 11, 11.5 up to 20 runs.

        :param line_interval: The line_interval of this MarketDefinition.
        :type: float
        """

        self._line_interval = line_interval

    @property
    def status(self):
        """
        Gets the status of this MarketDefinition.


        :return: The status of this MarketDefinition.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this MarketDefinition.


        :param status: The status of this MarketDefinition.
        :type: str
        """
        allowed_values = ["INACTIVE", "OPEN", "SUSPENDED", "CLOSED"]
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
