# coding: utf-8

"""
    Betfair: Exchange Streaming API

    API to receive streamed updates. This is an ssl socket connection of CRLF delimited json messages (see RequestMessage & ResponseMessage)

    OpenAPI spec version: 1.0.1423
    Contact: bdp@betfair.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class OrderSubscriptionMessage(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, op=None, id=None, segmentation_enabled=None, order_filter=None, clk=None, heartbeat_ms=None, initial_clk=None, conflate_ms=None):
        """
        OrderSubscriptionMessage - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'op': 'str',
            'id': 'int',
            'segmentation_enabled': 'bool',
            'order_filter': 'OrderFilter',
            'clk': 'str',
            'heartbeat_ms': 'int',
            'initial_clk': 'str',
            'conflate_ms': 'int'
        }

        self.attribute_map = {
            'op': 'op',
            'id': 'id',
            'segmentation_enabled': 'segmentationEnabled',
            'order_filter': 'orderFilter',
            'clk': 'clk',
            'heartbeat_ms': 'heartbeatMs',
            'initial_clk': 'initialClk',
            'conflate_ms': 'conflateMs'
        }

        self._op = op
        self._id = id
        self._segmentation_enabled = segmentation_enabled
        self._order_filter = order_filter
        self._clk = clk
        self._heartbeat_ms = heartbeat_ms
        self._initial_clk = initial_clk
        self._conflate_ms = conflate_ms

    @property
    def op(self):
        """
        Gets the op of this OrderSubscriptionMessage.
        The operation type

        :return: The op of this OrderSubscriptionMessage.
        :rtype: str
        """
        return self._op

    @op.setter
    def op(self, op):
        """
        Sets the op of this OrderSubscriptionMessage.
        The operation type

        :param op: The op of this OrderSubscriptionMessage.
        :type: str
        """

        self._op = op

    @property
    def id(self):
        """
        Gets the id of this OrderSubscriptionMessage.
        Client generated unique id to link request with response (like json rpc)

        :return: The id of this OrderSubscriptionMessage.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this OrderSubscriptionMessage.
        Client generated unique id to link request with response (like json rpc)

        :param id: The id of this OrderSubscriptionMessage.
        :type: int
        """

        self._id = id

    @property
    def segmentation_enabled(self):
        """
        Gets the segmentation_enabled of this OrderSubscriptionMessage.
        Segmentation Enabled - allow the server to send large sets of data in segments, instead of a single block

        :return: The segmentation_enabled of this OrderSubscriptionMessage.
        :rtype: bool
        """
        return self._segmentation_enabled

    @segmentation_enabled.setter
    def segmentation_enabled(self, segmentation_enabled):
        """
        Sets the segmentation_enabled of this OrderSubscriptionMessage.
        Segmentation Enabled - allow the server to send large sets of data in segments, instead of a single block

        :param segmentation_enabled: The segmentation_enabled of this OrderSubscriptionMessage.
        :type: bool
        """

        self._segmentation_enabled = segmentation_enabled

    @property
    def order_filter(self):
        """
        Gets the order_filter of this OrderSubscriptionMessage.
        Optional filter applied to order subscription

        :return: The order_filter of this OrderSubscriptionMessage.
        :rtype: OrderFilter
        """
        return self._order_filter

    @order_filter.setter
    def order_filter(self, order_filter):
        """
        Sets the order_filter of this OrderSubscriptionMessage.
        Optional filter applied to order subscription

        :param order_filter: The order_filter of this OrderSubscriptionMessage.
        :type: OrderFilter
        """

        self._order_filter = order_filter

    @property
    def clk(self):
        """
        Gets the clk of this OrderSubscriptionMessage.
        Token value delta (received in MarketChangeMessage) that should be passed to resume a subscription

        :return: The clk of this OrderSubscriptionMessage.
        :rtype: str
        """
        return self._clk

    @clk.setter
    def clk(self, clk):
        """
        Sets the clk of this OrderSubscriptionMessage.
        Token value delta (received in MarketChangeMessage) that should be passed to resume a subscription

        :param clk: The clk of this OrderSubscriptionMessage.
        :type: str
        """

        self._clk = clk

    @property
    def heartbeat_ms(self):
        """
        Gets the heartbeat_ms of this OrderSubscriptionMessage.
        Heartbeat Milliseconds - the heartbeat rate (looped back on initial image after validation: bounds are 500 to 5000)

        :return: The heartbeat_ms of this OrderSubscriptionMessage.
        :rtype: int
        """
        return self._heartbeat_ms

    @heartbeat_ms.setter
    def heartbeat_ms(self, heartbeat_ms):
        """
        Sets the heartbeat_ms of this OrderSubscriptionMessage.
        Heartbeat Milliseconds - the heartbeat rate (looped back on initial image after validation: bounds are 500 to 5000)

        :param heartbeat_ms: The heartbeat_ms of this OrderSubscriptionMessage.
        :type: int
        """

        self._heartbeat_ms = heartbeat_ms

    @property
    def initial_clk(self):
        """
        Gets the initial_clk of this OrderSubscriptionMessage.
        Token value (received in initial MarketChangeMessage) that should be passed to resume a subscription

        :return: The initial_clk of this OrderSubscriptionMessage.
        :rtype: str
        """
        return self._initial_clk

    @initial_clk.setter
    def initial_clk(self, initial_clk):
        """
        Sets the initial_clk of this OrderSubscriptionMessage.
        Token value (received in initial MarketChangeMessage) that should be passed to resume a subscription

        :param initial_clk: The initial_clk of this OrderSubscriptionMessage.
        :type: str
        """

        self._initial_clk = initial_clk

    @property
    def conflate_ms(self):
        """
        Gets the conflate_ms of this OrderSubscriptionMessage.
        Conflate Milliseconds - the conflation rate (looped back on initial image after validation: bounds are 0 to 120000)

        :return: The conflate_ms of this OrderSubscriptionMessage.
        :rtype: int
        """
        return self._conflate_ms

    @conflate_ms.setter
    def conflate_ms(self, conflate_ms):
        """
        Sets the conflate_ms of this OrderSubscriptionMessage.
        Conflate Milliseconds - the conflation rate (looped back on initial image after validation: bounds are 0 to 120000)

        :param conflate_ms: The conflate_ms of this OrderSubscriptionMessage.
        :type: int
        """

        self._conflate_ms = conflate_ms

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
